name: Node.js Publish

on:
    release:
        types: [created]

# on:
#     push:
#         branches:
#             - feature/actions

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - run: npm install -g npm
            - run: npm ci
            - run: npm run lint
            - run: npm test
              env:
                  SUMO_LOGIC_ENDPOINT: ${{ secrets.SUMO_LOGIC_ENDPOINT }}

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org/
            - run: npm install -g npm
            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
